### ISSUE TITLE
error importing package select

### ISSUE THREAD

**Issue by nskillen** [akissinger/sublime-polyml#2]
Running ST 2.0.1/2217 x64, was getting an import error in poly/process.py on the line "import select"

Sublime Text does still have select.pyd in its install folder, but apparently the polyml package couldn't find it. I copied the file over to the poly/ folder, and now it appears to be working fine.

**Comment by nskillen** [comment]
further problems...

Exception AttributeError: "PolyProcess instance has no attribute 'pipe'" in &lt;bound method PolyProcess.**del** of &lt;poly.process.PolyProcess instance at 0x0000000003BBE448&gt;&gt; ignored
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 339, in run_
  File ".\poly_console_here.py", line 11, in run
  File ".\poly\console.py", line 13, in **init**
NameError: global name 'sys' is not defined
